deploy:
  provider: pypi
  user: moritz.ploss
  password:
    secure: HJFY121bKkPytt/Nv8CHVepT5GR34lVN4AlbWsdryYOGBDbvJ6alvSm99oU3G1J0RcBsuNdnDIdqD1uPXyx0YEtqp1/RbIJs0xbIlqdudyZO1FiUf9o2ZzmwuTFecIK93Jk3GdeEUOQTXFBx/zHsd3q81366KRLw1p0nxJeWqb0AuXLQI63wNcWnbRs/D3h9xR/oJsBXSuncFDXrUYxdNlJdsWsTqc5zeTk81fJ8tPwxsavvmtrqDsKpgvp4NtEFGnRxdpiG+LTkMO0m9k+P6Sev+ZthafYBJkAajtFZtzLVn3MZHm6k1Y5SRs7h3TZt4C0RUYWd9yN+xh76j5bo6SCQ2uiDmByJyiEkpCyyyHD6XYEGxmnAwTB2Ye9uOi3Rr0Dy2zOjLXII1r7aXtpqGdGzyhpqWVk+DibtV+57y8jxBMQ+odax7gSfYX/unZ/fWmxnJHkeVBlb1beED2JWcGYzusiPDBldfSWPX6YMG1uX0054kEP764FddyFdDWguDXcGZxwzF6ZLbihN7IqGrMoj1Tvnb+qWRXuDzvpkXgbBY9iKPzktU0WA55yTHBKmGKbPyg6Whqj8y+UFZrPfqgK5xtDdJJidoEkciNDNW3y1PscIvbWUpSig96/9oT6rATJqKH4kVpmPxkU/02FYtZAR1n5L/Y/+3cwzTJvlyog=
  server: https://test.pypi.org/simple/
  distributions: sdist bdist_wheel
  on:
    tags: true
language: python
python:
- '3.6'
install:
- pip install .
- pip install pylint
- pip install -r requirements.txt
script:
- pytest tribology/tests/tests_tribology.py
