deploy:
  provider: pypi
  user: moritz.ploss
  password:
    secure: IwUKChBgOuy9HfLRI46gIv6mjOipnrLh6YfXLOKzGL+YSlmPZ+GL4G0CcmJylpKbWyKCNbv3yCXg1VO2aaBqlaU0serBhXrDRNNmQVrhqTetfZCVFRyE8QxhCa/lAqLqb1ZYUA16YfsYyQ4PW909khoBsDY6w344b/vC7k96mJnMen+75BaozU65YNkEW4VtQ70IHZN8NmcNygVgBuBfW5MHiIsP4xB2oeYAFIoLGX17HdM7k9IOLsqgcluKdnrY3T0gvRKc6ngzrwcwRTzYOqGG372hLV/kwnFhH+yCWsQ0rSQNIFvbGW6i/uPFF4/kKtukN+9zv/zzDzGnHGje6YBUVgrWeb/H+W5foiNBYAhc9GlGrTCmBFW5G/oHYfjWbLZPp4WjE15s0WgwtPw+dj1o2zYJATjR3fFxa6KLcgqGZ/+mvsGN5qcBcyU6DSsqWTGXBlFhJxXgHBLKE7jLBK2HofVZPQN4y1Dmu8IzqJ2oJ+To7VJ3wR5CjAQWr8hfQ5b4OLdjFPvyWsy1lRaJtsSCOiJUANKxRkv4k4cc0QkftDXWa8ewf3YnYmXX9DNvCfw2bQ4kp9PVUuiZ1W45Qps39S5sVKXNeW4M8N0TtwW73yb9DCJ11uPgvtRsygobnqhZOBMYaH7TZEDc/tyX0dsDw+YRR97UfJhfH9eO7Gc=
  distributions: sdist bdist_wheel
  on:
    tags: true
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install --upgrade bumpversion
- pip install sphinx
- pip install sphinxjp.themes.dotted
- pip install sphinx_rtd_theme
- pip install sphinxcontrib-fulltoc
- pip install pylint
- pip install -r requirements.txt
script:
- pytest tribology/tests/tests_tribology.py
- pylint --rcfile=tribology.pylintrc tribology -E --extension-pkg-whitelist=numpy
- sphinx-build -b html docs/sphinx_files/ docs/ -a
